title = "Wardlaw Eats"
baseURL = 'https://wardlaweats.bigshed.net/'

[author]
name = "Frederik Brooke Barnes"
email = "frederikbarnes@icloud.com"

[params]
  # "relatedtext" is the text that appears above the tag list at the bottom of pages.
  relatedtext = "Related"
  favicon = "/favicon.ico"

  #list items
  datesinlist = true
  authorsinlist = true

  #footer items
  nextprev = true
  taglist = true
  showrss = true

  tags = 5